version: '3.1'

services:

  app:
    image: backstage
    build: .
    entrypoint: /bin/sh -c "while ! nc -z db 5432; do sleep 3; done; yarn dev"
    environment:
      AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
      AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}
      GH_TOKEN: ${GH_TOKEN}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: &postgres-user postgres
      POSTGRES_PASSWORD: &postgres-pwd postgres
    ports:
      - 3000:3000
    volumes:
      - .:/home
      - /home/packages/node_modules

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USERNAME: *postgres-user
      POSTGRES_PASSWORD: *postgres-pwd
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
